source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftyImageIO_Example' do
  pod 'SwiftyImageIO', :path => '../'
end

target 'SwiftyImageIO_Tests' do
  pod 'SwiftyImageIO', :path => '../'
end
